# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate schema-based tracker C++ sources and CMake fragments from TOML manifests."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from template_renderer import render_template, render_with_copyright, template_values
from manifest import load_manifest
from templates import TrackerGenContext, enrich_context

COPYRIGHT = (
    "// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
    "// "
    "SPDX-License-Identifier: Apache-2.0\n\n"
    "// AUTO-GENERATED by src/core/codegen/generate_trackers.py — do not edit.\n\n"
)


def _write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only when it differs from the existing file.

    Returns True if the file was created or updated, False if left unchanged (mtime preserved).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_file():
        try:
            if path.read_text(encoding="utf-8") == content:
                return False
        except OSError:
            # Unreadable existing file — fall through and overwrite.
            pass
    path.write_text(content, encoding="utf-8")
    return True


def _join_lines(lines: Iterator[str]) -> str:
    return "\n".join(lines) + "\n"


def _render_tracker_set(ctx: TrackerGenContext, prefix: str) -> dict[str, str]:
    """Seven-file bundle: deviceio_base, facade hpp/cpp, live hpp/cpp, replay hpp/cpp."""
    return {
        f"deviceio_base/{ctx.base_header}.hpp": render_with_copyright(
            f"{prefix}/deviceio_base.hpp.template", ctx, COPYRIGHT
        ),
        f"deviceio_trackers/inc/deviceio_trackers/{ctx.header}.hpp": render_with_copyright(
            f"{prefix}/facade.hpp.template", ctx, COPYRIGHT
        ),
        f"deviceio_trackers/{ctx.header}.cpp": render_with_copyright(
            f"{prefix}/facade.cpp.template", ctx, COPYRIGHT
        ),
        f"live_trackers/{ctx.live_impl_file}.hpp": render_with_copyright(
            f"{prefix}/live.hpp.template", ctx, COPYRIGHT
        ),
        f"live_trackers/{ctx.live_impl_file}.cpp": render_with_copyright(
            f"{prefix}/live.cpp.template", ctx, COPYRIGHT
        ),
        f"replay_trackers/{ctx.replay_impl_file}.hpp": render_with_copyright(
            f"{prefix}/replay.hpp.template", ctx, COPYRIGHT
        ),
        f"replay_trackers/{ctx.replay_impl_file}.cpp": render_with_copyright(
            f"{prefix}/replay.cpp.template", ctx, COPYRIGHT
        ),
    }


def render_pull(ctx: TrackerGenContext) -> dict[str, str]:
    return _render_tracker_set(ctx, "pull")


def render_push(ctx: TrackerGenContext) -> dict[str, str]:
    return _render_tracker_set(ctx, "push")


def render_for_entry(ctx: TrackerGenContext) -> dict[str, str]:
    if ctx.direction == "push":
        return render_push(ctx)
    if ctx.shape != "single_collection":
        raise ValueError(f"tracker '{ctx.name}': unsupported shape '{ctx.shape}'")
    return render_pull(ctx)


def _render_fragment(name: str, ctx: TrackerGenContext) -> str:
    return render_template(f"fragments/{name}", template_values(ctx)).rstrip("\n")


def _gen_live_includes(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f'#include "{ctx.live_impl_file}.hpp"'
        yield f"#include <deviceio_trackers/{ctx.header}.hpp>"


def _gen_replay_includes(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f'#include "{ctx.replay_impl_file}.hpp"'
        yield f"#include <deviceio_trackers/{ctx.header}.hpp>"


def _gen_tracker_forward_decls(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f"class {ctx.cls};"
        yield f"class {ctx.iface};"


def _gen_live_try_create(entries: list[dict[str, Any]]) -> Iterator[str]:
    for index, entry in enumerate(entries):
        if index > 0:
            yield ""
        yield _render_fragment("live_try_create.template", enrich_context(entry))


def _gen_replay_try_create(entries: list[dict[str, Any]]) -> Iterator[str]:
    for index, entry in enumerate(entries):
        if index > 0:
            yield ""
        yield _render_fragment("replay_try_create.template", enrich_context(entry))


def _gen_live_dispatch_rows(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f"    make_dispatch_entry<{ctx.cls}, {ctx.live_impl}>(&try_create_{ctx.name}_impl),"


def _gen_replay_dispatch_rows(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f"    &try_create_{ctx.name}_impl,"


def _gen_factory_decls(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield (
            f"    std::unique_ptr<{ctx.iface}> create_{ctx.name}_tracker_impl"
            f"(const {ctx.cls}* tracker);"
        )


def _live_factory_template(ctx: TrackerGenContext) -> str:
    if ctx.direction == "push":
        return "live_factory_push.template"
    return "live_factory_pull.template"


def _replay_factory_template(ctx: TrackerGenContext) -> str:
    if ctx.direction == "push":
        return "replay_factory_push.template"
    if ctx.record:
        return "replay_factory_pull.template"
    return "replay_factory_pull_plain.template"


def _gen_all_live_factory_methods(entries: list[dict[str, Any]]) -> Iterator[str]:
    for index, entry in enumerate(entries):
        if index > 0:
            yield ""
        ctx = enrich_context(entry)
        yield _render_fragment(_live_factory_template(ctx), ctx)


def _gen_all_replay_factory_methods(entries: list[dict[str, Any]]) -> Iterator[str]:
    for index, entry in enumerate(entries):
        if index > 0:
            yield ""
        ctx = enrich_context(entry)
        yield _render_fragment(_replay_factory_template(ctx), ctx)


def _gen_recording_traits(ctx: TrackerGenContext) -> Iterator[str]:
    if ctx.direction != "pull" or not ctx.record:
        return
    if ctx.mcap_channels is None or ctx.replay_channels is None:
        raise ValueError(f"tracker '{ctx.name}': missing mcap/replay channels")
    yield from _render_fragment("recording_traits_pull.template", ctx).splitlines()


def _gen_all_recording_traits(entries: list[dict[str, Any]]) -> Iterator[str]:
    first = True
    for entry in entries:
        block = list(_gen_recording_traits(enrich_context(entry)))
        if not block:
            continue
        if not first:
            yield ""
        yield from block
        first = False


def _pybind_template(ctx: TrackerGenContext) -> str:
    if ctx.direction == "push":
        return "pybind_push.template"
    return "pybind_pull.template"


def _gen_pybind_blocks(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield _render_fragment(_pybind_template(ctx), ctx)


def _gen_tracker_binding_includes(entries: list[dict[str, Any]]) -> Iterator[str]:
    for entry in entries:
        ctx = enrich_context(entry)
        yield f"#include <deviceio_trackers/{ctx.header}.hpp>"


def _gen_python_tracker_exports(entries: list[dict[str, Any]]) -> Iterator[str]:
    yield "# AUTO-GENERATED"
    contexts = [enrich_context(entry) for entry in entries]
    for ctx in contexts:
        yield f"from ._deviceio_trackers import {ctx.cls}"
    yield ""
    yield "__all__ = ["
    for ctx in contexts:
        yield f'    "{ctx.cls}",'
    yield "]"


def emit_inc_fragments(entries: list[dict[str, Any]]) -> dict[str, str]:
    return {
        "inc/generated_live_includes.inc": _join_lines(_gen_live_includes(entries)),
        "inc/generated_tracker_forward_decls.inc": _join_lines(
            _gen_tracker_forward_decls(entries)
        ),
        "inc/generated_live_try_create.inc": _join_lines(_gen_live_try_create(entries)),
        "inc/generated_live_dispatch_rows.inc": _join_lines(
            _gen_live_dispatch_rows(entries)
        ),
        "inc/generated_live_factory_declarations.inc": _join_lines(
            _gen_factory_decls(entries)
        ),
        "inc/generated_live_factory_methods.inc": _join_lines(
            _gen_all_live_factory_methods(entries)
        ),
        "inc/generated_replay_includes.inc": _join_lines(_gen_replay_includes(entries)),
        "inc/generated_replay_try_create.inc": _join_lines(
            _gen_replay_try_create(entries)
        ),
        "inc/generated_replay_dispatch_rows.inc": _join_lines(
            _gen_replay_dispatch_rows(entries)
        ),
        "inc/generated_replay_factory_declarations.inc": _join_lines(
            _gen_factory_decls(entries)
        ),
        "inc/generated_replay_factory_methods.inc": _join_lines(
            _gen_all_replay_factory_methods(entries)
        ),
        "inc/generated_recording_traits.inc": _join_lines(
            _gen_all_recording_traits(entries)
        ),
        "inc/generated_tracker_binding_includes.inc": _join_lines(
            _gen_tracker_binding_includes(entries)
        ),
        "inc/generated_tracker_bindings.inc": _join_lines(_gen_pybind_blocks(entries)),
        "python/_generated_tracker_exports.py": _join_lines(
            _gen_python_tracker_exports(entries)
        ),
    }


def _gen_cmake_source_list(name: str, items: list[str]) -> Iterator[str]:
    yield f"set({name}"
    for item in items:
        yield f'  "${{GENERATED_TRACKER_DIR}}/{item}"'
    yield ")"


def _gen_cmake_content(sources: list[str], out_dir: Path) -> Iterator[str]:
    facade: list[str] = []
    live: list[str] = []
    replay: list[str] = []
    for src in sources:
        if src.startswith("deviceio_trackers/"):
            facade.append(src)
        elif src.startswith("live_trackers/"):
            live.append(src)
        elif src.startswith("replay_trackers/"):
            replay.append(src)

    yield "# AUTO-GENERATED by generate_trackers.py"
    yield f'set(GENERATED_TRACKER_DIR "{out_dir}")'
    yield from _gen_cmake_source_list("GENERATED_TRACKER_FACADE_SOURCES", facade)
    yield from _gen_cmake_source_list("GENERATED_TRACKER_LIVE_SOURCES", live)
    yield from _gen_cmake_source_list("GENERATED_TRACKER_REPLAY_SOURCES", replay)
    yield "set(GENERATED_TRACKER_DEVICEIO_BASE_INC_DIR ${GENERATED_TRACKER_DIR})"
    yield "set(GENERATED_TRACKER_DEVICEIO_TRACKERS_INC_DIR ${GENERATED_TRACKER_DIR}/deviceio_trackers/inc)"
    yield "set(GENERATED_TRACKER_LIVE_IMPL_INC_DIR ${GENERATED_TRACKER_DIR}/live_trackers)"
    yield "set(GENERATED_TRACKER_REPLAY_IMPL_INC_DIR ${GENERATED_TRACKER_DIR}/replay_trackers)"
    yield "set(GENERATED_TRACKER_INC_DIR ${GENERATED_TRACKER_DIR}/inc)"


def emit_cmake(sources: list[str], out_dir: Path) -> str:
    return _join_lines(_gen_cmake_content(sources, out_dir))


OWNERSHIP_MARKER = ".isaac_teleop_tracker_codegen"
_PRUNE_SUFFIXES = frozenset({".hpp", ".cpp", ".inc", ".py", ".cmake"})
_AUTO_GENERATED_HEAD = b"AUTO-GENERATED"
_PRUNE_HEAD_BYTES = 512


def _write_ownership_marker(out_dir: Path) -> Path:
    marker = out_dir / OWNERSHIP_MARKER
    content = "isaac_teleop tracker codegen\n"
    _write_if_changed(marker, content)
    return marker


def _is_generator_owned_file(path: Path) -> bool:
    if path.name == OWNERSHIP_MARKER:
        return False
    if path.suffix not in _PRUNE_SUFFIXES:
        return False
    try:
        head = path.read_bytes()[:_PRUNE_HEAD_BYTES]
    except OSError:
        return False
    return _AUTO_GENERATED_HEAD in head


def _prune_stale(out_dir: Path, keep: set[Path]) -> None:
    """Delete previously generated files this run did not emit (opt-in via ``--prune-stale``).

    Why: generated include dirs sit on the compiler search path. After a rename or removal,
    an old header can keep satisfying a stale ``#include`` instead of failing the build.
    Pruning removes those orphans so outdated includes break loudly.

    Only runs when ``OWNERSHIP_MARKER`` is present. Unlinks only files with a known generated
    suffix and an AUTO-GENERATED banner in the first 512 bytes.
    """
    if not out_dir.is_dir():
        return
    if not (out_dir / OWNERSHIP_MARKER).is_file():
        return
    for path in out_dir.rglob("*"):
        if not path.is_file():
            continue
        if path.resolve() in keep:
            continue
        if not _is_generator_owned_file(path):
            continue
        path.unlink()


def generate(
    manifest_path: Path,
    defaults_path: Path,
    out_dir: Path,
    cmake_path: Path,
    *,
    prune_stale: bool = False,
) -> None:
    entries = load_manifest(manifest_path, defaults_path)
    all_sources: list[str] = []
    written: set[Path] = set()
    for entry in entries:
        ctx = enrich_context(entry)
        files = render_for_entry(ctx)
        for rel, content in files.items():
            _write_if_changed(out_dir / rel, content)
            written.add((out_dir / rel).resolve())
            if rel.endswith((".cpp", ".hpp")):
                all_sources.append(rel)

    inc_files = emit_inc_fragments(entries)
    for rel, content in inc_files.items():
        _write_if_changed(out_dir / rel, content)
        written.add((out_dir / rel).resolve())

    _write_if_changed(
        cmake_path, emit_cmake(sorted(set(all_sources)), out_dir.resolve())
    )
    written.add(cmake_path.resolve())

    marker = _write_ownership_marker(out_dir)
    written.add(marker.resolve())

    if prune_stale:
        _prune_stale(out_dir, written)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--defaults", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--emit-cmake", type=Path, required=True)
    parser.add_argument(
        "--prune-stale",
        action="store_true",
        help=(
            "Delete previously generated files under --out-dir that this run did not emit "
            "(so renamed trackers cannot leave old headers satisfying stale #includes). "
            "CMake configure passes this flag; omit it for dry/manual runs that only rewrite."
        ),
    )
    parser.add_argument("--print-resolved", action="store_true")
    args = parser.parse_args(argv)

    if args.print_resolved:
        from manifest import print_resolved

        print_resolved(args.manifest, args.defaults)
        return 0

    generate(
        args.manifest,
        args.defaults,
        args.out_dir,
        args.emit_cmake,
        prune_stale=args.prune_stale,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
