# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""C++ and Python code templates for generated schema-based trackers."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


def _header() -> str:
    return (
        "// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "\n"
        "// AUTO-GENERATED by src/core/codegen/generate_trackers.py — do not edit.\n"
        "\n"
    )


@dataclass(frozen=True, slots=True)
class TrackerGenContext:
    """Resolved manifest entry plus derived C++/file names for codegen."""

    name: str
    table: str
    direction: str
    shape: str
    schema: str
    cls: str
    tensor_identifier: str
    localized_name: str
    channel: str
    schema_name: str
    traits: str
    python_accessor: str
    max_flatbuffer_size: int
    record: bool
    facade_tensor_constant: bool
    mcap_channels: tuple[str, ...] | None
    replay_channels: tuple[str, ...] | None
    header: str
    base_header: str
    live_impl_file: str
    replay_impl_file: str
    iface: str
    record_type: str
    data_type: str
    fb_table: str
    mcap_channels_type: str
    schema_tracker_type: str
    mcap_viewers_type: str
    live_impl: str
    replay_impl: str


def enrich_context(entry: dict[str, Any]) -> TrackerGenContext:
    cls = entry["class"]
    table = entry["table"]
    name = entry["name"]
    # Optional manifest `header` keeps public #include stems when `name` alone would
    # invent a different path (e.g. frame_metadata_oak → frame_metadata_tracker_oak).
    header_override = entry.get("header")
    if header_override is not None:
        header = str(header_override)
        base = f"{header}_base"
        live_impl_file = f"live_{header}_impl"
        replay_impl_file = f"replay_{header}_impl"
    elif name.endswith("_tracker"):
        header = name
        base = f"{name}_base"
        live_impl_file = f"live_{name}_impl"
        replay_impl_file = f"replay_{name}_impl"
    else:
        header = f"{name}_tracker"
        base = f"{name}_tracker_base"
        live_impl_file = f"live_{name}_tracker_impl"
        replay_impl_file = f"replay_{name}_tracker_impl"

    mcap_raw = entry.get("mcap_channels")
    replay_raw = entry.get("replay_channels")
    mcap_channels = tuple(mcap_raw) if mcap_raw is not None else None
    replay_channels = tuple(replay_raw) if replay_raw is not None else None

    return TrackerGenContext(
        name=name,
        table=table,
        direction=str(entry["direction"]),
        shape=str(entry["shape"]),
        schema=str(entry["schema"]),
        cls=str(cls),
        tensor_identifier=str(entry["tensor_identifier"]),
        localized_name=str(entry["localized_name"]),
        channel=str(entry["channel"]),
        schema_name=str(entry["schema_name"]),
        traits=str(entry["traits"]),
        python_accessor=str(entry["python_accessor"]),
        max_flatbuffer_size=int(entry["max_flatbuffer_size"]),
        record=bool(entry["record"]),
        facade_tensor_constant=bool(entry["facade_tensor_constant"]),
        mcap_channels=mcap_channels,
        replay_channels=replay_channels,
        header=header,
        base_header=base,
        live_impl_file=live_impl_file,
        replay_impl_file=replay_impl_file,
        iface=f"I{cls}Impl",
        record_type=f"{table}Record",
        data_type=f"{table}T",
        fb_table=table,
        mcap_channels_type=f"{cls}McapChannels",
        schema_tracker_type=f"{cls}SchemaTracker",
        mcap_viewers_type=f"{cls}McapViewers",
        live_impl=f"Live{cls}Impl",
        replay_impl=f"Replay{cls}Impl",
    )
