# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Unit tests for generator output writes and stale-file pruning."""

from __future__ import annotations

import tempfile
import time
import unittest
from pathlib import Path

from generate_trackers import (
    _is_generator_owned_file,
    _prune_stale,
    _write_if_changed,
    _write_ownership_marker,
    generate,
)


class WriteIfChangedTest(unittest.TestCase):
    def test_skips_write_when_content_matches(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "out.hpp"
            path.write_text("// AUTO-GENERATED\nsame\n", encoding="utf-8")
            before = path.stat().st_mtime_ns
            time.sleep(0.01)
            changed = _write_if_changed(path, "// AUTO-GENERATED\nsame\n")
            self.assertFalse(changed)
            self.assertEqual(path.stat().st_mtime_ns, before)

    def test_writes_when_content_differs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "out.hpp"
            path.write_text("old\n", encoding="utf-8")
            before = path.stat().st_mtime_ns
            time.sleep(0.01)
            changed = _write_if_changed(path, "new\n")
            self.assertTrue(changed)
            self.assertEqual(path.read_text(encoding="utf-8"), "new\n")
            self.assertGreater(path.stat().st_mtime_ns, before)


class PruneStaleTest(unittest.TestCase):
    def test_no_prune_without_ownership_marker(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            stale = out_dir / "stale.hpp"
            stale.write_text("// AUTO-GENERATED\n", encoding="utf-8")
            _prune_stale(out_dir, keep=set())
            self.assertTrue(stale.is_file())

    def test_stale_generated_file_removed(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            _write_ownership_marker(out_dir)
            stale = out_dir / "stale.hpp"
            stale.write_text(
                "// AUTO-GENERATED by generate_trackers.py\n", encoding="utf-8"
            )
            _prune_stale(out_dir, keep=set())
            self.assertFalse(stale.is_file())

    def test_foreign_file_without_banner_survives(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            _write_ownership_marker(out_dir)
            foreign = out_dir / "hand_written.hpp"
            foreign.write_text("#pragma once\n", encoding="utf-8")
            _prune_stale(out_dir, keep=set())
            self.assertTrue(foreign.is_file())

    def test_is_generator_owned_rejects_wrong_suffix(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "notes.txt"
            path.write_text("AUTO-GENERATED\n", encoding="utf-8")
            self.assertFalse(_is_generator_owned_file(path))

    def test_ownership_marker_never_pruned_as_generated(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            marker = _write_ownership_marker(out_dir)
            self.assertFalse(_is_generator_owned_file(marker))

    def test_generate_default_does_not_prune(self) -> None:
        core = Path(__file__).resolve().parents[1]
        manifest = core / "deviceio_trackers" / "trackers.toml"
        defaults = core / "deviceio_trackers" / "defaults.toml"
        if not manifest.is_file():
            self.skipTest("trackers.toml missing")
        with tempfile.TemporaryDirectory() as tmp:
            out_dir = Path(tmp)
            orphan = out_dir / "deviceio_trackers" / "orphan_tracker.cpp"
            orphan.parent.mkdir(parents=True)
            orphan.write_text(
                "// AUTO-GENERATED by generate_trackers.py\n", encoding="utf-8"
            )
            generate(
                manifest,
                defaults,
                out_dir,
                out_dir / "generated_sources.cmake",
                prune_stale=False,
            )
            self.assertTrue(orphan.is_file())
            generate(
                manifest,
                defaults,
                out_dir,
                out_dir / "generated_sources.cmake",
                prune_stale=True,
            )
            self.assertFalse(orphan.is_file())


if __name__ == "__main__":
    unittest.main()
